name: ugd_4_hospital
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  barcode_widget: ^2.0.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.8
  flutter_svg: ^2.0.9
  flutter_tts: ^3.8.3
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.4.0
  geocoding: ^2.0.4
  geolocator: ^10.1.0
  grouped_list: ^4.2.0
  http: ^1.1.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.4
  intl: ^0.17.0
  ionicons: ^0.2.2
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  pdf: ^3.10.6
  permission_handler: ^11.0.1
  printing: ^5.11.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  responsive_sizer: ^3.2.0
  sensors_plus: ^3.1.0
  shared_preferences: ^2.0.6
  sqflite: ^2.2.6
  url_launcher: ^6.1.10
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3

flutter:
  uses-material-design: true
  assets:
    - images/